spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springDatabase
    username: postgres
    password: passer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true